# Generated by Django 5.0.4 on 2024-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
